<<<<<<< HEAD

twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
=======
twig:
    default_path: '%kernel.project_dir%/templates'

when@test:
    twig:
        strict_variables: true
>>>>>>> 0a2dda5ad602af99a9b661ffb1c7c47b3b6697ec
